### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this file 

### ISSUE THREAD

**Issue by javafish** [CurryTang/Graph-LLM#4]
Hi, when I try to change a model, e.g., from deberta-base to deberta-v3-base, I got below errors. Can u pls tell me how to solve it? Thx

    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like microsoft/deberta-v3-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by CurryTang** [comment]
Hello,

Given the information at hand, I'm uncertain about the root cause of this issue. However, here are some potential reasons to consider:

Please ensure that you've added the mapping in `get_model_name_mapping`.
Verify that the model name is accurate(It seems now it's trying to load models from disks instead of downloading them). For instance, it should be `microsoft/deberta-v3-base`.
It's worth noting that we utilize HuggingFace's core API to load the language model, so there shouldn't typically be any issues on that front.
